### ISSUE TITLE
[Feat]: 自动化版本构建与发布

### ISSUE THREAD

**Issue by Luna-Grace** [DuckDuckStudio/Fufu_Dev_Tools#15]
### 对新功能/建议的描述

如题

### 为什么需要实现此功能 (可选)

可以节省很多人工费时

### 对于实施该功能的方法的建议 (可选)

可以根据现有的自动打包脚本改改写个无人值守的脚本然后放到GitHub Action里run。
但有个问题，就是打包脚本炸了没法人工解决：
- 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。 - 如果真有这个问题可以让工作流炸下然后手动打包

**Comment by DuckDuckStudio** [comment]
触发条件设为手动触发还是依据commit触发？
